name: gpt-cli
version: git
summary: A fast CSV command line toolkit written in Rust
description: ok

base: core20
confinement: devmode
grade: devel

parts:
  gpt-cli:
    plugin: rust
    source: .
    build-packages:
      - libxcb1-dev
      - libxcb-render0-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
    stage-packages:
      - libxau6
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xfixes0
      - libxcb1
      - libxdmcp6
#    build-packages:
#      - xorg-dev
#      - libxcb-composite0-dev
#      - libxcb1-dev
#      - libxcb-render0-dev
#      - libxcb-shape0-dev
#      - libxcb-xfixes0-dev
apps:
  gpt-cli:
    command: bin/gpt-cli
    plugs: [network, network-bind]
