name: Debug

on:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install base-devel
        run: |
          pacman -Syu --noconfirm base-devel wget bc git openssh
      - name: Setup environment
        run: |
          echo "PKGVER=0.0.14" >> $GITHUB_ENV
          echo "PKGREL=$(echo "1+$(curl "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=gpt-cli" | head -n 3 | tail -n 1 | cut -d "=" -f 2)" | bc)" >> $GITHUB_ENV
      - run: echo ${{ env.PKGVER }}
      - name: Setup environment2
        run: |
          wget "https://github.com/gustawdaniel/gpt-cli/releases/download/v${{ env.PKGVER }}/gpt-cli" -O gpt-cli.gnu
          echo "CHECKSUM=$(sha512sum gpt-cli.gnu | cut -d " " -f 1)" >> $GITHUB_ENV

      - name: Prepare PKGBUILD
        run: |
          cat <<EOT >> PKGBUILD
          pkgname=gpt-cli
          pkgver=${{ env.PKGVER }}
          pkgrel=${{ env.PKGREL }}
          pkgdesc="Run linux commands with natural language. Eg 'show my graphic card' instead 'lspci | grep VGA'"
          arch=('x86_64')
          url="https://github.com/gustawdaniel/gpt-cli"
          license=('MIT')
          depends=('xorg-server-devel' 'libxcb')
          options=()
          source_x86_64=("https://github.com/gustawdaniel/gpt-cli/releases/download/v${{ env.PKGVER }}/gpt-cli.gnu")
          sha512sums_x86_64=('${{ env.CHECKSUM }}')
          
          package() {
          # Install the binary
          install -Dm755 "\$srcdir/gpt-cli" "\$pkgdir/usr/bin/gpt-cli"
          
          # Create a symbolic link
          ln -s "/usr/bin/gpt-cli" "\$pkgdir/usr/bin/p"
          }
          EOT

      - name: Generate .SRCINFO
        run: |
          useradd -m builduser
          passwd -d builduser
          echo "builduser ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builduser
          chown -R builduser:builduser .
          sudo -u builduser bash -c "makepkg --printsrcinfo > .SRCINFO"

      - name: Show files
        run: |
          ls -la
          cat PKGBUILD
          cat .SRCINFO

      - run: mkdir -p /github/home/.ssh

#      - name: Add known host
#        run: |
#          echo 'aur.archlinux.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDM1We1tROGx+WRp6hAfW7t8il22SfLwzkK/GvFqWd8JfD4WrK4tQEKLiONdJsiG8rNCKOObQw2NlIuR87kNp9/9y7ZFpGU+r3d59zKb1D0iTJ7U+lLZjKd6Ugm9XzoACx7SCoK5J5V5Q2r+I/xQwF7aHnLqrJcRgB4j4n4u4pT8zW9zf9p3I3+q3qig2YYTgJhL+w+H7RfAdMj2gW6d/9v1Bxi/5yY6U8W6UZ/xvUO3Lq3sx6j8V7yX5+5D5J1u5F1bMsfZu0AaGk7+sLm6Kj7Vd42vfeDZR7Vr5r5ibl7Ku+cFZQ2QENu5iZ8QGLHWXgMj+mVV6iRFBzH8U6WjUv' >> ~/.ssh/known_hosts

      - run: ls -la /github/home/.ssh
      - run: cat /github/home/.ssh/config
      - run: |
          cat <<EOT >> /github/home/.ssh/config
          Host *
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null
          EOT
      - run: sudo chmod 400 /github/home/.ssh/config
      - run: echo "${{ secrets.ID_ED25519 }}" > /github/home/.ssh/id_ed25519
      - run: echo "${{ secrets.ID_ED25519_PUB }}" > /github/home/.ssh/id_ed25519.pub
      - run: chmod 600 /github/home/.ssh/id_ed25519
      - run: git config --global user.email "gustaw.daniel@gmail.com"
      - run: git config --global user.name "Daniel Gustaw"
      - run: git init
#      - run: git config --unset-all http.https://github.com/.extraheader
      - run: ls -la /github/home/.ssh
      - run: whoami
      - run: ls -la /
      - run: ls -la /__w
      - run: git config --global --add safe.directory /__w/gpt-cli/gpt-cli
      - run: git remote add aur ssh://aur@aur.archlinux.org/gpt-cli.git

      - name: Commit and push
        run: |
          git add PKGBUILD .SRCINFO
          git commit -m "Release ${{ env.PKGVER }}-${{ env.PKGREL }}"
          git push aur HEAD:master