name: Debug

on:
#  push:
#    branches: ['*']
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install clipboard deps
        run: sudo apt install xorg-dev libxcb-composite0-dev
      - run: cargo build --target x86_64-unknown-linux-gnu --release
#      - run: cargo publish
#        env:
#          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}