name: Install

on:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - uses: actions/checkout@v3
      - run: apt update -y
      - run: apt install wget sudo -y
      - run: ./install.sh
      - run: apt install shunit2 -y
      - run: ./test_version.sh

  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora
    steps:
      - uses: actions/checkout@v3
      - run: dnf install wget sudo -y
      - run: ./install.sh
      - run: dnf install shunit2 -y
      - run: ./test_version.sh

  archlinux:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v3
      - run: pacman -Sy wget sudo --noconfirm
      - run: ./install.sh
      - run: |
          curl -L https://github.com/kward/shunit2/releases/download/2.1.8/shunit2 -o /usr/local/bin/shunit2
          chmod +x /usr/local/bin/shunit2
      - run: ./test_version.sh

  opensuse:
    runs-on: ubuntu-latest
    container:
      image: opensuse
    steps:
      - uses: actions/checkout@v3
      - run: zypper install wget sudo -y
      - run: ./install.sh
      - run: |
          curl -L https://github.com/kward/shunit2/releases/download/2.1.8/shunit2 -o /usr/local/bin/shunit2
          chmod +x /usr/local/bin/shunit2
      - run: ./test_version.sh