name: Debug

on:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - uses: actions/checkout@v3
      - run: apt install wget sudo -y
      - run: ./install.sh
      - run: apt install shunit2 -y
      - run: ./test_version.sh

  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora
    steps:
      - uses: actions/checkout@v3
      - run: dnf install wget sudo -y
      - run: ./install.sh
      - run: dnf install shunit2 -y
      - run: ./test_version.sh

  archlinux:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v3
      - run: pacman -S install wget sudo --noconfirm
      - run: ./install.sh
      - run: pacman -S install shunit2 --noconfirm
      - run: ./test_version.sh