name: Install

on:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - uses: actions/checkout@v3
      - run: apt update -y
      - run: apt install wget sudo -y
      - run: ./install.sh
      - run: apt install shunit2 -y
      - run: ./test_version.sh

  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora
    steps:
      - uses: actions/checkout@v3
      - run: dnf install wget sudo -y
      - run: ./install.sh
      - run: dnf install shunit2 -y
      - run: ./test_version.sh

  archlinux:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v3
      - run: pacman -Sy wget sudo --noconfirm
      - run: ./install.sh
      - run: |
          curl -sLo /usr/local/bin/shunit2 https://raw.githubusercontent.com/kward/shunit2/master/shunit2
          chmod +x /usr/local/bin/shunit2
          mkdir -p /usr/share/shunit2
          ln -s /usr/local/bin/shunit2 /usr/share/shunit2/shunit2
      - run: cat Cargo.toml
      - run: grep -E "^version" Cargo.toml
      - run: grep -E "^version" Cargo.toml | cut -d "\"" -f 2
      - run: ./test_version.sh

  opensuse:
    runs-on: ubuntu-latest
    container:
      image: opensuse/leap
    steps:
      - run: zypper --non-interactive install wget sudo tar
      - uses: actions/checkout@v3
      - run: ./install.sh
      - run: |
          curl -sLo /usr/local/bin/shunit2 https://raw.githubusercontent.com/kward/shunit2/master/shunit2
          chmod +x /usr/local/bin/shunit2
          mkdir -p /usr/share/shunit2
          ln -s /usr/local/bin/shunit2 /usr/share/shunit2/shunit2
      - run: ./test_version.sh

  alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:
      - uses: actions/checkout@v3
      - run: apk add wget sudo bash -f
      - run: ./install.sh
      - run: |
          curl -sLo /usr/local/bin/shunit2 https://raw.githubusercontent.com/kward/shunit2/master/shunit2
          chmod +x /usr/local/bin/shunit2
          mkdir -p /usr/share/shunit2
          ln -s /usr/local/bin/shunit2 /usr/share/shunit2/shunit2
      - run: ./test_version.sh
